name: Run SortedArray tests
run-name: ${{ github.actor }} is running SortedArray tests
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run test
      - run: npm run coverage-lcov
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
